name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run this workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-22.04  # Make sure the Ubuntu version is compatible

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Build Docker image
        run: |
          docker build -t my-image .
          docker images
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      # Step 4: Run tests
      - name: Run tests
        run: pytest --maxfail=5 --disable-warnings